services:
  web:
    build: .
    image: mecfs-paperwork:prod
    expose:
      - "8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    init: true
    read_only: true
    tmpfs:
      - /tmp
      - /var/run:uid=65532,gid=65532,mode=0755
      - /var/cache/nginx:uid=65532,gid=65532,mode=0755
      - /var/cache/nginx/client_temp:uid=65532,gid=65532,mode=0755
      - /var/log/nginx:uid=65532,gid=65532,mode=0755
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  caddy:
    image: caddy:2-alpine
    depends_on:
      web:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    init: true
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
  # Checks both that Caddy is alive and that the upstream app is reachable.
      test: ["CMD-SHELL", "caddy version >/dev/null 2>&1 && wget -qO- http://web:8080/ >/dev/null 2>&1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s



volumes:
  caddy_data:
  caddy_config:
