services:
  web:
    build: .
    image: mecfs-paperwork:prod
    expose:
      - "80"
    restart: unless-stopped
    init: true
    read_only: true
    tmpfs:
      - /tmp
      - /var/run:uid=65532,gid=65532,mode=0755
      - /var/cache/nginx:uid=65532,gid=65532,mode=0755
      - /var/cache/nginx/client_temp:uid=65532,gid=65532,mode=0755
      - /var/log/nginx:uid=65532,gid=65532,mode=0755
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "nginx -t"]
      interval: 10s
      timeout: 2s
      retries: 10

  caddy:
    image: caddy:2-alpine
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    init: true
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "caddy", "version"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  caddy_data:
  caddy_config:
